cat > buildspec.yml << 'EOF'
version: 0.2

phases:
  install:
    commands:
      - echo "Install phase OK"

  build:
    commands:
      - echo "Build phase OK"

artifacts:
  files:
    - '**/*'
EOF

