version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws --version
      - ECR_REPO_URI=$(aws ecr describe-repositories --repository-names "$ECR_REPO_NAME" --query 'repositories[0].repositoryUri' --output text)
      - echo "ECR_REPO_URI=$ECR_REPO_URI"
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin "$ECR_REPO_URI"

  build:
    commands:
      - echo "Build started on $(date)"
      - echo "Building Docker image..."
      - docker build -t "$ECR_REPO_URI:latest" .

  post_build:
    commands:
      - echo "Pushing Docker image to ECR..."
      - docker push "$ECR_REPO_URI:latest"
      - echo "Forcing ECS service deployment..."
      - aws ecs update-service --cluster te-ai-chatbot-dev --service te-ai-chatbot-dev --force-new-deployment
      - echo "Tagging commit in GitHub..."
      - chmod +x scripts/tag_commit.sh
      - ./scripts/tag_commit.sh   # SHA возьмётся из CODEBUILD_RESOLVED_SOURCE_VERSION

artifacts:
  files:
    - '**/*'

